# Generated by Django 5.2.1 on 2025-05-08 21:07

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="body",
            field=markdownx.models.MarkdownxField(default=""),
        ),
    ]
